Repository umbraco-community/awesome-umbraco, pull requests merged in 2019-01, with the labels that each got.

#48 Add personalisation groups
  README.md
Labels: addition, approved

#49 Add stacked content
  README.md
Labels: addition, approved

#46 Added "v7 Dialog Expander" and "Inline HTML Help"
  README.md
Labels: addition, approved, author-submitted

#51 Addition of Courier and Deploy contrib repos
  README.md
Labels: addition, approved

#52 Add the Health checks package
  README.md
Labels: addition, approved

#53 Update around courier and deploy
  README.md
Labels: approved
